### PR TITLE
Upgrade of iOS sdk to 5.2 that supports building with xcode 7

### PR DESCRIPTION
**Pull request by fmaceachen**
With this upgrade we will be able to build the plugin with xcode 7 and support iOS9

### CODE REVIEW

**Comment by vkeepe** [comment]
BitCode support plugin size is right now too large. See https://github.com/card-io/card.io-iOS-SDK/issues/119

Updated all the libs except the libCardIO.a

For now 5.1.0 libCardIO.a is working fine with Xcode 7 and iOS9. Added support to external hook for unzip the file for future need.

**Comment by stephan-nordnes-eriksen** [comment]
I am running into issues with `.../com.keepe.cardio/libCardIO.a(libCardIO.a-arm64-master.o)' does not contain bitcode. ...`

What should I do to fix this?

**Comment by vkeepe** [comment]
Disable bitcode for now in Xcode for your project. Right now I have not imported the bitcode enabled libraries from CardIO as it is too large. Hoping someone at Paypal will get the size to be manageable.

**Comment by stephan-nordnes-eriksen** [comment]
I wonder: Could you maybe split the large file into multi-part zip files? Would love to implement your library, but it is essentially useless for ios without bitcode enabled. I get it to build when turning off bitcode, but I suspect I will face issues when trying to submit to app store.

**Comment by vkeepe** [comment]
My App is already in the store with current library. I have the implementation already done with bitcode enabled but the libraries are too big. Will review again.

**Pull request closed without merging**
